on: [push, pull_request]
name: package
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}
    
    env:
      CC: 'clang'
      CXX: 'clang++'
      CONAN_USER_HOME: "${{ github.workspace }}/release"
      CONAN_USER_HOME_SHORT: "${{ github.workspace }}/release/short"
      INSTALL_DIR: ${{ github.workspace }}/install/
      
    steps:
      - name: Perform checkout
        uses: actions/checkout@v2
        
      - name: Install Python environment 
        uses: actions/setup-python@v2
        
      - name: Install conan
        run: |
            pip install conan --upgrade
            conan profile new default --detect
            conan profile update settings.compiler=clang default
            conan profile update settings.compiler.version=11 default

      - name: Mac build
        if: matrix.os == 'macos-latest'
        run: |
            brew install automake
            conan profile update settings.compiler.libcxx=libc++ default
            chmod +x build.sh
            ./build.sh
            conan install . --build=missing
            cmake . -DCMAKE_BUILD_TYPE=Release
            cmake --build . --config Release
            ./bin/tests
